/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 19/09/2021 17:45:50        ****/
/******************************************************************************/

SET NAMES NONE;

/*CREATE DATABASE 'LOCALHOST:D:\_Projetos\Exemplo1\CONTROLE_PEDIDO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;
*/


/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_TB_PEDIDOITENS;
SET GENERATOR GEN_TB_PEDIDOITENS TO 0;

CREATE GENERATOR GEN_TB_PEDIDO_ID;
SET GENERATOR GEN_TB_PEDIDO_ID TO 0;

CREATE GENERATOR GEN_TB_PRODUTO_ID;
SET GENERATOR GEN_TB_PRODUTO_ID TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TB_PEDIDO (
    IDPEDIDO        INTEGER NOT NULL,
    DATAEMISSAO     DATE,
    TOTAL_PRODUTOS  NUMERIC(15,2) NOT NULL
);

CREATE TABLE TB_PEDIDOITENS (
    IDPEDIDOITENS  INTEGER NOT NULL,
    IDPEDIDO       INTEGER NOT NULL,
    IDPRODUTO      INTEGER NOT NULL,
    QTDE           NUMERIC(15,2) NOT NULL,
    PUNITARIO      NUMERIC(15,2) NOT NULL,
    SUBTOTAL       NUMERIC(15,2) NOT NULL
);

CREATE TABLE TB_PRODUTO (
    IDPRODUTO    INTEGER NOT NULL,
    NOMEPRODUTO  VARCHAR(60),
    PVENDA       NUMERIC(15,2)
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TB_PEDIDO ADD CONSTRAINT PK_TB_PEDIDO PRIMARY KEY (IDPEDIDO);
ALTER TABLE TB_PEDIDOITENS ADD CONSTRAINT PK_TB_PEDIDOITENS PRIMARY KEY (IDPEDIDOITENS);
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_TB_PRODUTO PRIMARY KEY (IDPRODUTO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TB_PEDIDOITENS ADD CONSTRAINT FK_TB_PEDIDOITENS_1 FOREIGN KEY (IDPEDIDO) REFERENCES TB_PEDIDO (IDPEDIDO);
ALTER TABLE TB_PEDIDOITENS ADD CONSTRAINT FK_TB_PEDIDOITENS_2 FOREIGN KEY (IDPRODUTO) REFERENCES TB_PRODUTO (IDPRODUTO);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TB_PEDIDOITENS_BI */
CREATE TRIGGER TB_PEDIDOITENS_BI FOR TB_PEDIDOITENS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idpedidoitens is null) then
    new.idpedidoitens = gen_id(GEN_TB_PEDIDOITENS, 1);
end
^

/* Trigger: TB_PEDIDO_BI */
CREATE TRIGGER TB_PEDIDO_BI FOR TB_PEDIDO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idpedido is null) then
    new.idpedido = gen_id(GEN_TB_PEDIDO_ID, 1);
end
^

/* Trigger: TB_PRODUTO_BI */
CREATE TRIGGER TB_PRODUTO_BI FOR TB_PRODUTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idproduto is null) then
    new.idproduto = gen_id(gen_tb_produto_id,1);
end
^
SET TERM ; ^

